### PR TITLE
Fix user based api calls and forms.

### LINKED ISSUE #154: Fix user based api calls and forms.

### PR DESCRIPTION
**Pull request by johndavis92790**
- Fix login and sign-up pages.
- Add login nevbar option when no user is logged in, change to logout when the user has logged in.
- Fix user based api calls with mongoDB.
- Refactor component and page function calls for more consistency across the app.
- Create useStates for currentUserEmail and currentUser to keep track of current user after logging in and to be able to access the user information from anywhere within the app.

### CODE REVIEW

File: client/src/App.tsx [hunk 1]
```diff
@@ -1,30 +1,34 @@
...
-      const response = await fetch("/api/user/user", {
+      const response = await fetch(`${apiServer()}/api/user/get-user`, {
+        method: "POST",
         headers: { "Content-Type": "application/json" },
         credentials: "include",
       });
       const content = await response.json();
-      setCurrentUserEmail(content.username);
+      setCurrentUserEmail(content.email);
+      setCurrentUser(content);
```
Comment (robyng) [inline client/src/App.tsx]: does this need to be content.username?

File: client/src/utils/helpers.tsx [hunk 2]
```diff
@@ -1,23 +1,19 @@
-function apiServer() {
+export function apiServer() {
   const url = window.location.href;
   const slice = url.slice(0, 21);
-  if (slice === 'http://localhost:3000') {
-    return 'http://localhost:3001'
-  } else {
+  if (slice === "http://localhost:3000") {
+    return "http://localhost:3001";
+  } else if (slice === "https://dragon-fruit-") {
```
Comment (robyng) [inline client/src/utils/helpers.tsx:6]: Should the slice be https://dragon-fruit-app ?

**Review by robyng — CHANGES_REQUESTED** [review]
Alright doing export const... from now on! Just a few questions that I had.

File: client/src/App.tsx (hunk 1 above)
Comment (johndavis92790) [reply client/src/App.tsx]: Do we want to have users login with a username or email? I can set it up either way, you choose

File: client/src/utils/helpers.tsx (hunk 2 above)
Comment (johndavis92790) [reply client/src/utils/helpers.tsx:6]: No because this has to be the first 22 characters. This is kind of a hacky way to get the API to work in both local and live environments. I will eventually find a better, less hacky way, but this was super easy for now and works fine.

File: client/src/App.tsx (hunk 1 above)
Comment (johndavis92790) [reply client/src/App.tsx]: I remember now, I used email because thats how David setup the login page, but we can change that. You let me know how you want it setup and I will take care of it.

Comment (robyng) [reply client/src/App.tsx]: Okay I see what you are saying where Login has email field, we should keep it as that then. Future development would be great for the field to accept either email or username to login.

File: client/src/utils/helpers.tsx (hunk 2 above)
Comment (robyng) [reply client/src/utils/helpers.tsx:6]: Okay! I see you this is how your identifying live or local environment for the API. Thanks. If we ever change our domain name we would need to update this here.

**Review by robyng — APPROVED** [review]

**Comment by robyng** [comment]
Some funky things happening when I pull down and test and try sign up or login. Console shows endless errors of user unauthorized and doesn't show token in applications. Maybe I'm missing something?

File: server/controller/userController.js [hunk 3]
```diff
@@ -1,10 +1,10 @@
-const axios = require("axios");
+// const axios = require('axios');
 const bcrypt = require("bcryptjs");
 const jwt = require("jsonwebtoken");
```
Comment (robyng) [inline server/controller/userController.js:2]: Does a web token show when you login? No tokens are showing for me when I test.

**Review by robyng — CHANGES_REQUESTED** [review]

File: server/controller/userController.js (hunk 3 above)
Comment (johndavis92790) [reply server/controller/userController.js:2]: If you haven't yet, please update your .env file, maybe that will fix this. I sent you the info on Slack.

**Review by robyng — APPROVED** [review]

**Comment by robyng** [comment]
Thanks, seeing token in the cookies. Would like to have the sign up be able to login automatically instead of sing up  then login. Will make a feature development ticket for it.

**Comment by johndavis92790** [comment]
> Thanks, seeing token in the cookies. Would like to have the sign up be able to login automatically instead of sing up then login. Will make a feature development ticket for it.

Ya thats fine, this is the simpler approach so to save time I did it this way but we can change it later no problem.
