### PR TITLE
Fix serverCalls.tsx

### LINKED ISSUE #139: Fix serverCalls.tsx

### PR DESCRIPTION
**Pull request by johndavis92790**
- Fix FavRestaurant API calls.
- Remove saveRestaurant API since it is no longer needed.

### CODE REVIEW

File: client/src/components/NavBar/NavBar.tsx [hunk 1]
```diff
@@ -110,7 +118,6 @@ export function Navbar(props: any) {
         <Link to={"/single-result/ChIJn58N1B9gUocRpAXOXPbFcOo"}>
           Single Result
         </Link>
-      </details>
```
Comment (robyng) [inline client/src/components/NavBar/NavBar.tsx]: keep details

**Review by robyng — CHANGES_REQUESTED** [review]

File: client/src/components/NavBar/NavBar.tsx (hunk 1 above)
Comment (johndavis92790) [reply client/src/components/NavBar/NavBar.tsx]: Answer is in PR 140

**Review by MatteoThomas — APPROVED** [review]
